#!/usr/bin/js

/*
Triangular, pentagonal, and hexagonal
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following 
formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

// Note: This would be faster using inverse functions on the hexagonals!

var upperBound = 10000000000;
var hexagonals = new Set();
var pentaHex = new Set();
var hn = 0;
var pn = 0;
var tn = 0;

for (n = 143+1; hn < upperBound; n++) {
    var hn = n*(2*n-1);
    hexagonals.add(hn);
}

for (n = 165+1; pn < upperBound; n++) {
    var pn = n*(3*n-1)/2;
    if (hexagonals.has(pn)) {
        pentaHex.add(pn);
    }
}

for (n = 285+1; tn < upperBound; n++) {
    var tn = n*(n+1)/2;
    if (pentaHex.has(tn)) {
        console.log("It's " + tn + "!");
        break;
    }
}
