/*
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
*/

#include <stdio.h>
#include <math.h>

int count_divisors(int n)
{
    int divisors = 0;
    int root = sqrt(n);
    if (root % 1 == 0)
        divisors = 1;

    for (int i = 1; i < root; i++)
        if (n % i == 0)
            divisors += 2;

    return divisors;
}

int main()
{
    int divisors = 0;
    int number = 1;
    int term = 1;

    while (divisors <= 500)
    {
        printf("Term %d is %d, with %d divisors\n", term, number, divisors);
        number += term+1;
        term += 1;
        divisors = count_divisors(number);
    }

    printf("The answer, with %d divisors, is...\n", divisors);
    printf("%d\n", number);
}
