#!/usr/bin/env python3

'''
Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten 
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of 
D?
'''

pn_set = set()
pn_list = []
for n in range(1, 10000):
    pn = int(n*(3*n-1)/2)
    pn_set.add(pn)
    pn_list.append(pn)

for i, n in enumerate(pn_list):
    for j, m in enumerate(pn_list[i+1:]):
        if m-n in pn_set and n+m in pn_set:
            print((n, m), m-n)
